package com.garganttua.api.spec.engine;

public interface IRefreshableAuthorizationMethodBinderBuilder extends IMethodBinderBuilder<IRefreshableAuthorizationMethodBinderBuilder, IRefreshableAuthorizationBuilder>{

}
