<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.garganttua</groupId>
		<artifactId>garganttua-api-dao</artifactId>
		<version>3.0.0-ALPHA01</version>
	</parent>
	<artifactId>garganttua-api-dao-mongodb</artifactId>

	<properties>
		<mongodb-driver.version>5.1.1</mongodb-driver.version>
	</properties>

	<dependencies>
		<!-- Garganttua API -->
		<dependency>
			<groupId>com.garganttua</groupId>
			<artifactId>garganttua-api-spec</artifactId>
		</dependency>

		<!-- MongoDB Driver -->
		<dependency>
			<groupId>org.mongodb</groupId>
			<artifactId>mongodb-driver-sync</artifactId>
			<version>${mongodb-driver.version}</version>
		</dependency>

	</dependencies>
</project>
