name: Maven Package

on:
  push:
    branches: 
      - "*"  # Build on any branch push
    tags:
      - "*"  # Trigger on any tag creation

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        server-id: github-garganttua-api
        settings-path: ${{ github.workspace }}

    - name: Generate Maven Settings
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        output_file: package-settings.xml
<<<<<<< HEAD
        servers: >
=======
        repositories: >
>>>>>>> 1401c7b (Update maven-publish.yml)
          [
            {
<<<<<<< HEAD
              "id": "github garganttua tooling",
=======
              "id": "github",
              "url": "https://maven.pkg.github.com/garganttua/garganttua-tooling"
            }
          ]
        servers: >
          [
            {
              "id": "github",
>>>>>>> 3e270c2 (Update maven-publish.yml)
              "username": "${{ github.actor }}",
<<<<<<< HEAD
              "password": "${{ github.token }}"
=======
              "password": " ${{ github.token }}"
>>>>>>> ba2e248 (Update maven-publish.yml)
            }
          ]

    - name: Build with Maven
      run: mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/package-settings.xml
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        server-id: github garganttua api
		
    - name: Deploy to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}